[package]
name = "hello-rust-lang"
version = "0.1.0"
authors = ["Batman <57849598+eat-sleep-code-repeat-it@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"